// Generated via https://jeremyrsellars.github.io/slate-cljs-walkthroughs/closure_externs.html
// from NPM.

// Reference ns as slate-history or use global js/SlateHistory
/**********************************************************************
 * Extern for global SlateHistory
 * Generated by https://jeremyrsellars.github.io/slate-cljs-walkthroughs/closure_externs.html
 **********************************************************************/
var SlateHistory = {
    "HISTORY": {},
    "History": {
        "isHistory": function() {},
    },
    "HistoryEditor": {
        "isHistoryEditor": function() {},
        "isMerging": function() {},
        "isSaving": function() {},
        "redo": function() {},
        "undo": function() {},
        "withoutMerging": function() {},
        "withoutSaving": function() {},
    },
    "MERGING": {},
    "SAVING": {},
    "withHistory": function() {},
};
